package internation.controller;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.util.ResourceBundle;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import internation.dao.GetListVideo;
import internation.model.Flag;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Tab;
import javafx.scene.text.Text;

public class ControlController implements Initializable {

	// Biến để Browse Images
	String filename = null;
	BufferedImage bi;

	Flag flag = new Flag();
	VideoController video = new VideoController();
	// Stage stage1 = new Stage();
	// Stage stage2 = new Stage();
	// Stage stage3 = new Stage();

	@FXML
	private Tab pnBasic;
	@FXML
	private Tab pnVideo;
	@FXML
	private Tab pnHistory;
	@FXML
	private Button btnBrowseVideo;
	@FXML
	private Button btnBrowseSub;
	@FXML
	private Text txtVideo;
	@FXML
	private Text txtSub;
	@FXML
	private Button btnInsert;
	@FXML
	private Text txtResult;
   

	int a = 0;
int b= 0;
	// Event Listener on Tab[#pnBasic].onSelectionChanged
	@FXML
	public void BasicLoad(Event event) {
		// TODO Autogenerated
		flag.setfReview(true);
		flag.setfStudyVideo(true);
		// if (flag.isfBasic() == true) {
		// System.out.println("hello");
		// flag.setfBasic(false);
		// }

//		Image imgbrowse = new Image(getClass().getResourceAsStream("Images/browse.png"));
		btnBrowseVideo.setOnAction(new EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {
//				Button button = (Button) event.getSource();
//				btnBrowseVideo= new Button("Browse video");
//				btnBrowseVideo.setGraphic(new ImageView(imgbrowse));
				// File
				FileInputStream inp;

		// 		Chọn file video từ máy tính 
				JFileChooser fileChooser = new JFileChooser();
				FileNameExtensionFilter filter = new FileNameExtensionFilter("*.mp4", "*.mp3");
				fileChooser.setFileFilter(filter);

				int i = fileChooser.showOpenDialog(null);
				if (i == JFileChooser.APPROVE_OPTION) {
					File file = fileChooser.getSelectedFile();
					System.out.println(file);
					filename = file.getAbsolutePath();
					txtVideo.setText(filename);
					a = 1;

				}

			}
		});

		btnBrowseSub.setOnAction(new EventHandler<ActionEvent>() {

			@Override
			public void handle(ActionEvent event) {
				 
				//Chọn file video từ máy tính 
				JFileChooser fileChooser = new JFileChooser();
				FileNameExtensionFilter filter = new FileNameExtensionFilter("*.srt", "*.xls");
				fileChooser.setFileFilter(filter);
				
				int i = fileChooser.showOpenDialog(null);
				if (i == JFileChooser.APPROVE_OPTION) {
					File file = fileChooser.getSelectedFile();
					System.out.println(file);
					filename = file.getAbsolutePath();
					txtSub.setText(filename);
					b = 1;

				}
			}
		});

		btnInsert.setOnAction(new EventHandler<ActionEvent>() {
			@Override
			public void handle(ActionEvent event) {

				if (a == 1 & b==1) {

					int kt = GetListVideo.InsertPathVideo(filename);

					if (kt == 1) {
						System.out.println("Insert successfully");
						txtResult.setText("Insert successfully");
					} else {
						System.out.println("Insert fail");
						txtResult.setText("Insert Fail");
					}
				} else {
					JOptionPane.showMessageDialog(null, "Bạn chưa chọn file video hoặc chưa chọn file sub");
				}

			}
		});

	}

	// Event Listener on Tab[#pnVideo].onSelectionChanged
	@FXML
	public void StudyVideoLoad(Event event) {
		// TODO Autogenerated
		flag.setfBasic(true);
		flag.setfReview(true);
		if (flag.isfStudyVideo() == true) {
			try {
				if(pnVideo.getContent()==null) {
					Parent root = FXMLLoader.load(getClass().getResource("/internation/ListVideo.fxml"));
					pnVideo.setContent(root);
				}
				

			} catch (Exception e) {
				e.printStackTrace();
			}
			flag.setfStudyVideo(false);
		}
	}

	// Event Listener on Tab[#pnHistory].onSelectionChanged
	@FXML
	public void HistoryLoad(Event event) {
		// TODO Autogenerated
		flag.setfBasic(true);
		flag.setfStudyVideo(true);
		// stage1.close();
		if (flag.isfReview() == true) {
			try {
				Parent root = FXMLLoader.load(getClass().getResource("/internation/History.fxml"));
				pnHistory.setContent(root);

			} catch (Exception e) {
				e.printStackTrace();
			}
			flag.setfReview(false);
		}
	}

	@FXML
	public void HelpLoad(Event event) {
		// TODO Autogenerated
		flag.setfBasic(true);
		flag.setfStudyVideo(true);
		flag.setfReview(true);
		// stage1.close();

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		flag.setfBasic(true);
		flag.setfReview(true);
		flag.setfBasic(true);
		flag.setfHelp(true);
	}

}
