package internation.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.net.URL;
import java.util.ResourceBundle;

import internation.model.Flag;
import internation.controller.VideoController;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Tab;
import javafx.stage.Stage;
import javafx.event.Event;

public class ControlController implements Initializable{
	
	Flag flag = new Flag();
	VideoController video = new VideoController();
	//Stage stage1 = new Stage();
	//Stage stage2 = new Stage();
	//Stage stage3 = new Stage();
	
	@FXML
	private Tab pnBasic;
	@FXML
	private Tab pnVideo;
	@FXML
	private Tab pnHistory;

	// Event Listener on Tab[#pnBasic].onSelectionChanged
	@FXML
	public void BasicLoad(Event event) {
		// TODO Autogenerated
		flag.setfReview(true);
		flag.setfStudyVideo(true);
		if(flag.isfBasic()==true)
		{
		System.out.println("hello");
		flag.setfBasic(false);
		}
	}
	// Event Listener on Tab[#pnVideo].onSelectionChanged
	@FXML
	public void StudyVideoLoad(Event event) {
		// TODO Autogenerated
		flag.setfBasic(true);
		flag.setfReview(true);
		if(flag.isfStudyVideo()==true)
		{
			try {				
				Parent root = FXMLLoader.load(getClass().getResource("/internation/ListVideo.fxml"));
	            pnVideo.setContent(root);
	            
	            
		} catch(Exception e) {
				e.printStackTrace();
			}
		flag.setfStudyVideo(false);
		}
	}
	// Event Listener on Tab[#pnHistory].onSelectionChanged
	@FXML
	public void HistoryLoad(Event event) {
		// TODO Autogenerated
		flag.setfBasic(true);
		flag.setfStudyVideo(true);
		//stage1.close();
		if(flag.isfReview()==true)
		{
			try {				
				Parent root = FXMLLoader.load(getClass().getResource("/internation/History.fxml"));
	            pnHistory.setContent(root);
	            
		} catch(Exception e) {
				e.printStackTrace();
			}
			flag.setfReview(false);
		}
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		flag.setfBasic(true);
		flag.setfReview(true);
		flag.setfBasic(true);
	}
}
