package internation.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Slider;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.stage.Stage;

import java.awt.Label;
import java.net.URL;
import java.time.Duration;
import java.util.ResourceBundle;

import internation.*;
import javafx.event.ActionEvent;

public class IntroController implements Initializable{
	
	@FXML
	private Button btnStart;
	@FXML
	private ImageView imgIntro;
	
	private Image img = new Image("/Images/paner.png");
	public void initialize(URL location, ResourceBundle resources) {

		imgIntro.setImage(img);
	}
	// Event Listener on Button[#btnStart].onAction
	@FXML
	public void startLearning(ActionEvent event) {
		// TODO Autogenerated
		try {
<<<<<<< HEAD
			
=======
			Stage stage1 = (Stage) btnStart.getScene().getWindow();
		    // do what you have to do
		    stage1.close();
>>>>>>> 229722e0dfff9de89bbf88de8a8b77f0e86a9021
			Parent root = FXMLLoader.load(getClass().getResource("/internation/Control.fxml"));
			Stage stage = new Stage();
            stage.setTitle("English Intonation");
            stage.setScene(new Scene(root, 1050, 450));
            stage.show();

	} catch(Exception e) {
			e.printStackTrace();
		}
	}
}
